### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/vqaxxxxxx.jpg

### ISSUE THREAD

**Issue by LZY-233** [pliang279/MultiViz#39]
When I run the vqa_lxmert_unimodallime.py, I get an error of FileNotFoundError just likeFileNotFoundError: [Errno 2] No such file or directory: 'tmp/vqa87721637.jpg' and I have downloaded the dataset as you asked and and unzip all in a folder named structured-framework/data. I don't know how to fix this error, can you help me fix it? thank you.
my environment is
- ubuntu20.04
- python3.8
- torch2.0.0
- cuda11.8
The following is the complete error message
Traceback (most recent call last):
  File "examples/vqa_lxmert_unimodallime.py", line 22, in <module>
    explanation1 = rununimodallime(
  File "/root/autodl-tmp/MultiViz/structured-framework/analysis/unimodallime.py", line 65, in rununimodallime
    return lime_explainer.explain_instance(
  File "/root/miniconda3/lib/python3.8/site-packages/lime/lime_image.py", line 198, in explain_instance
    data, labels = self.data_labels(image, fudged_image, segments,
  File "/root/miniconda3/lib/python3.8/site-packages/lime/lime_image.py", line 261, in data_labels
    preds = classifier_fn(np.array(imgs))
  File "/root/autodl-tmp/MultiViz/structured-framework/analysis/unimodallime.py", line 27, in classify
    modifiedinputs = [
  File "/root/autodl-tmp/MultiViz/structured-framework/analysis/unimodallime.py", line 28, in <listcomp>
    analysismodel.replaceunimodaldata(datainstance, modalityname, i)
  File "/root/autodl-tmp/MultiViz/structured-framework/models/vqa_lxmert.py", line 119, in replaceunimodaldata
    plt.imsave(randname, newinput)
  File "/root/miniconda3/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2200, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/matplotlib/image.py", line 1689, in imsave
    image.save(fname, **pil_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/PIL/Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/vqa87721637.jpg'

**Comment by LZY-233** [comment]
Just to add, I didn't change the code
